// <auto-generated />
using System;
using Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Api.Migrations
{
    [DbContext(typeof(PaylocityDbContext))]
    [Migration("20240525015228_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Api.Models.Dependent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Relationship")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Dependents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(2010, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4927),
                            EmployeeId = 1,
                            FirstName = "Aurora",
                            LastName = "Young",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4997),
                            EmployeeId = 1,
                            FirstName = "Carter",
                            LastName = "Allen",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5003),
                            EmployeeId = 1,
                            FirstName = "Zoey",
                            LastName = "King",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(2019, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5007),
                            EmployeeId = 2,
                            FirstName = "Carter",
                            LastName = "Allen",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(2005, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5011),
                            EmployeeId = 2,
                            FirstName = "Zoey",
                            LastName = "King",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(2024, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5015),
                            EmployeeId = 3,
                            FirstName = "Zoey",
                            LastName = "King",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(2009, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5019),
                            EmployeeId = 3,
                            FirstName = "Owen",
                            LastName = "Wright",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(2020, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5024),
                            EmployeeId = 3,
                            FirstName = "Hannah",
                            LastName = "Scott",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(2014, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5027),
                            EmployeeId = 3,
                            FirstName = "Wyatt",
                            LastName = "Torres",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(2024, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5032),
                            EmployeeId = 3,
                            FirstName = "Penelope",
                            LastName = "Nguyen",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(2002, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5036),
                            EmployeeId = 4,
                            FirstName = "Owen",
                            LastName = "Wright",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5040),
                            EmployeeId = 4,
                            FirstName = "Hannah",
                            LastName = "Scott",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(2008, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5044),
                            EmployeeId = 4,
                            FirstName = "Wyatt",
                            LastName = "Torres",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5047),
                            EmployeeId = 5,
                            FirstName = "Hannah",
                            LastName = "Scott",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(2004, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5051),
                            EmployeeId = 5,
                            FirstName = "Wyatt",
                            LastName = "Torres",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(2023, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5094),
                            EmployeeId = 6,
                            FirstName = "Wyatt",
                            LastName = "Torres",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(2006, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5099),
                            EmployeeId = 6,
                            FirstName = "Penelope",
                            LastName = "Nguyen",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(2000, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5103),
                            EmployeeId = 6,
                            FirstName = "John",
                            LastName = "Hill",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5107),
                            EmployeeId = 7,
                            FirstName = "Penelope",
                            LastName = "Nguyen",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5110),
                            EmployeeId = 7,
                            FirstName = "John",
                            LastName = "Hill",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(2005, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5114),
                            EmployeeId = 7,
                            FirstName = "Layla",
                            LastName = "Flores",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(2010, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5118),
                            EmployeeId = 7,
                            FirstName = "Jack",
                            LastName = "Green",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(2007, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5121),
                            EmployeeId = 7,
                            FirstName = "Lillian",
                            LastName = "Adams",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(2000, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5125),
                            EmployeeId = 8,
                            FirstName = "John",
                            LastName = "Hill",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5128),
                            EmployeeId = 8,
                            FirstName = "Layla",
                            LastName = "Flores",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(2015, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5131),
                            EmployeeId = 8,
                            FirstName = "Jack",
                            LastName = "Green",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(2004, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5135),
                            EmployeeId = 8,
                            FirstName = "Lillian",
                            LastName = "Adams",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(2018, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5138),
                            EmployeeId = 8,
                            FirstName = "Luke",
                            LastName = "Nelson",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5142),
                            EmployeeId = 9,
                            FirstName = "Layla",
                            LastName = "Flores",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(2009, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5145),
                            EmployeeId = 9,
                            FirstName = "Jack",
                            LastName = "Green",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 31,
                            DateOfBirth = new DateTime(2018, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5148),
                            EmployeeId = 10,
                            FirstName = "Jack",
                            LastName = "Green",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 32,
                            DateOfBirth = new DateTime(2015, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5151),
                            EmployeeId = 10,
                            FirstName = "Lillian",
                            LastName = "Adams",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 33,
                            DateOfBirth = new DateTime(2004, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5154),
                            EmployeeId = 10,
                            FirstName = "Luke",
                            LastName = "Nelson",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 34,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5159),
                            EmployeeId = 11,
                            FirstName = "Lillian",
                            LastName = "Adams",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 35,
                            DateOfBirth = new DateTime(2010, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5162),
                            EmployeeId = 11,
                            FirstName = "Luke",
                            LastName = "Nelson",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 36,
                            DateOfBirth = new DateTime(2017, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5165),
                            EmployeeId = 11,
                            FirstName = "Addison",
                            LastName = "Baker",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 37,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5169),
                            EmployeeId = 12,
                            FirstName = "Luke",
                            LastName = "Nelson",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 38,
                            DateOfBirth = new DateTime(2005, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5200),
                            EmployeeId = 12,
                            FirstName = "Addison",
                            LastName = "Baker",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 39,
                            DateOfBirth = new DateTime(2019, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5204),
                            EmployeeId = 12,
                            FirstName = "Daniel",
                            LastName = "Hall",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 40,
                            DateOfBirth = new DateTime(2023, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5207),
                            EmployeeId = 12,
                            FirstName = "Eleanor",
                            LastName = "Rivera",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 41,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5211),
                            EmployeeId = 13,
                            FirstName = "Addison",
                            LastName = "Baker",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 42,
                            DateOfBirth = new DateTime(2020, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5215),
                            EmployeeId = 13,
                            FirstName = "Daniel",
                            LastName = "Hall",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 43,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5219),
                            EmployeeId = 13,
                            FirstName = "Eleanor",
                            LastName = "Rivera",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 44,
                            DateOfBirth = new DateTime(2024, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5222),
                            EmployeeId = 13,
                            FirstName = "Gabriel",
                            LastName = "Campbell",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 45,
                            DateOfBirth = new DateTime(2008, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5226),
                            EmployeeId = 14,
                            FirstName = "Daniel",
                            LastName = "Hall",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 46,
                            DateOfBirth = new DateTime(2014, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5230),
                            EmployeeId = 14,
                            FirstName = "Eleanor",
                            LastName = "Rivera",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 47,
                            DateOfBirth = new DateTime(2004, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5233),
                            EmployeeId = 14,
                            FirstName = "Gabriel",
                            LastName = "Campbell",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 48,
                            DateOfBirth = new DateTime(2015, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5237),
                            EmployeeId = 15,
                            FirstName = "Eleanor",
                            LastName = "Rivera",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 49,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5240),
                            EmployeeId = 15,
                            FirstName = "Gabriel",
                            LastName = "Campbell",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 50,
                            DateOfBirth = new DateTime(2011, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5243),
                            EmployeeId = 15,
                            FirstName = "Natalie",
                            LastName = "Mitchell",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 51,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5246),
                            EmployeeId = 16,
                            FirstName = "Gabriel",
                            LastName = "Campbell",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 52,
                            DateOfBirth = new DateTime(2007, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5249),
                            EmployeeId = 16,
                            FirstName = "Natalie",
                            LastName = "Mitchell",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 53,
                            DateOfBirth = new DateTime(2014, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5253),
                            EmployeeId = 16,
                            FirstName = "Logan",
                            LastName = "Carter",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 54,
                            DateOfBirth = new DateTime(2017, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5256),
                            EmployeeId = 16,
                            FirstName = "Savannah",
                            LastName = "Roberts",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 55,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5260),
                            EmployeeId = 17,
                            FirstName = "Natalie",
                            LastName = "Mitchell",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 56,
                            DateOfBirth = new DateTime(2015, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5263),
                            EmployeeId = 17,
                            FirstName = "Logan",
                            LastName = "Carter",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 57,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5266),
                            EmployeeId = 17,
                            FirstName = "Savannah",
                            LastName = "Roberts",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 58,
                            DateOfBirth = new DateTime(2012, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5269),
                            EmployeeId = 17,
                            FirstName = "Anthony",
                            LastName = "Gomez",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 59,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5273),
                            EmployeeId = 18,
                            FirstName = "Logan",
                            LastName = "Carter",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 60,
                            DateOfBirth = new DateTime(2005, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5276),
                            EmployeeId = 18,
                            FirstName = "Savannah",
                            LastName = "Roberts",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 61,
                            DateOfBirth = new DateTime(2017, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5279),
                            EmployeeId = 18,
                            FirstName = "Anthony",
                            LastName = "Gomez",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 62,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5283),
                            EmployeeId = 19,
                            FirstName = "Savannah",
                            LastName = "Roberts",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 63,
                            DateOfBirth = new DateTime(2018, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5312),
                            EmployeeId = 19,
                            FirstName = "Anthony",
                            LastName = "Gomez",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 64,
                            DateOfBirth = new DateTime(2020, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5315),
                            EmployeeId = 19,
                            FirstName = "Isla",
                            LastName = "Phillips",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 65,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5319),
                            EmployeeId = 19,
                            FirstName = "Isaac",
                            LastName = "Evans",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 66,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5324),
                            EmployeeId = 20,
                            FirstName = "Anthony",
                            LastName = "Gomez",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 67,
                            DateOfBirth = new DateTime(2008, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5327),
                            EmployeeId = 20,
                            FirstName = "Isla",
                            LastName = "Phillips",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 68,
                            DateOfBirth = new DateTime(2008, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5331),
                            EmployeeId = 20,
                            FirstName = "Isaac",
                            LastName = "Evans",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 69,
                            DateOfBirth = new DateTime(2002, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5334),
                            EmployeeId = 20,
                            FirstName = "Hazel",
                            LastName = "Turner",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 70,
                            DateOfBirth = new DateTime(2024, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5338),
                            EmployeeId = 20,
                            FirstName = "Julian",
                            LastName = "Diaz",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 71,
                            DateOfBirth = new DateTime(2011, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5341),
                            EmployeeId = 21,
                            FirstName = "Isla",
                            LastName = "Phillips",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 72,
                            DateOfBirth = new DateTime(2006, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5344),
                            EmployeeId = 21,
                            FirstName = "Isaac",
                            LastName = "Evans",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 73,
                            DateOfBirth = new DateTime(2019, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5348),
                            EmployeeId = 21,
                            FirstName = "Hazel",
                            LastName = "Turner",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 74,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5351),
                            EmployeeId = 21,
                            FirstName = "Julian",
                            LastName = "Diaz",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 75,
                            DateOfBirth = new DateTime(2014, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5354),
                            EmployeeId = 22,
                            FirstName = "Isaac",
                            LastName = "Evans",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 76,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5358),
                            EmployeeId = 22,
                            FirstName = "Hazel",
                            LastName = "Turner",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 77,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5361),
                            EmployeeId = 22,
                            FirstName = "Julian",
                            LastName = "Diaz",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 78,
                            DateOfBirth = new DateTime(2016, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5364),
                            EmployeeId = 22,
                            FirstName = "Violet",
                            LastName = "Parker",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 79,
                            DateOfBirth = new DateTime(2020, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5368),
                            EmployeeId = 23,
                            FirstName = "Hazel",
                            LastName = "Turner",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 80,
                            DateOfBirth = new DateTime(2000, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5371),
                            EmployeeId = 23,
                            FirstName = "Julian",
                            LastName = "Diaz",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 81,
                            DateOfBirth = new DateTime(2007, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5374),
                            EmployeeId = 23,
                            FirstName = "Violet",
                            LastName = "Parker",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 82,
                            DateOfBirth = new DateTime(2008, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5378),
                            EmployeeId = 24,
                            FirstName = "Julian",
                            LastName = "Diaz",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 83,
                            DateOfBirth = new DateTime(2014, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5381),
                            EmployeeId = 24,
                            FirstName = "Violet",
                            LastName = "Parker",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 84,
                            DateOfBirth = new DateTime(2007, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5384),
                            EmployeeId = 24,
                            FirstName = "Levi",
                            LastName = "Cruz",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 85,
                            DateOfBirth = new DateTime(2010, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5412),
                            EmployeeId = 24,
                            FirstName = "Aubrey",
                            LastName = "Edwards",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 86,
                            DateOfBirth = new DateTime(2002, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5416),
                            EmployeeId = 25,
                            FirstName = "Violet",
                            LastName = "Parker",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 87,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5419),
                            EmployeeId = 25,
                            FirstName = "Levi",
                            LastName = "Cruz",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 88,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5423),
                            EmployeeId = 26,
                            FirstName = "Levi",
                            LastName = "Cruz",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 89,
                            DateOfBirth = new DateTime(2018, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5427),
                            EmployeeId = 26,
                            FirstName = "Aubrey",
                            LastName = "Edwards",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 90,
                            DateOfBirth = new DateTime(2008, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5430),
                            EmployeeId = 26,
                            FirstName = "Ryan",
                            LastName = "Collins",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 91,
                            DateOfBirth = new DateTime(2017, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5434),
                            EmployeeId = 26,
                            FirstName = "Claire",
                            LastName = "Reyes",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 92,
                            DateOfBirth = new DateTime(2013, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5437),
                            EmployeeId = 27,
                            FirstName = "Aubrey",
                            LastName = "Edwards",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 93,
                            DateOfBirth = new DateTime(2006, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5440),
                            EmployeeId = 27,
                            FirstName = "Ryan",
                            LastName = "Collins",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 94,
                            DateOfBirth = new DateTime(2023, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5444),
                            EmployeeId = 27,
                            FirstName = "Claire",
                            LastName = "Reyes",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 95,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5447),
                            EmployeeId = 28,
                            FirstName = "Ryan",
                            LastName = "Collins",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 96,
                            DateOfBirth = new DateTime(2006, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5451),
                            EmployeeId = 28,
                            FirstName = "Claire",
                            LastName = "Reyes",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 97,
                            DateOfBirth = new DateTime(2010, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5454),
                            EmployeeId = 28,
                            FirstName = "Ethan",
                            LastName = "Brooks",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 98,
                            DateOfBirth = new DateTime(2019, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5457),
                            EmployeeId = 28,
                            FirstName = "Madison",
                            LastName = "Powell",
                            Relationship = 3
                        },
                        new
                        {
                            Id = 99,
                            DateOfBirth = new DateTime(2015, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5461),
                            EmployeeId = 29,
                            FirstName = "Claire",
                            LastName = "Reyes",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 100,
                            DateOfBirth = new DateTime(2004, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5464),
                            EmployeeId = 29,
                            FirstName = "Ethan",
                            LastName = "Brooks",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 101,
                            DateOfBirth = new DateTime(2004, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5467),
                            EmployeeId = 29,
                            FirstName = "Madison",
                            LastName = "Powell",
                            Relationship = 1
                        },
                        new
                        {
                            Id = 102,
                            DateOfBirth = new DateTime(2018, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5471),
                            EmployeeId = 30,
                            FirstName = "Ethan",
                            LastName = "Brooks",
                            Relationship = 0
                        },
                        new
                        {
                            Id = 103,
                            DateOfBirth = new DateTime(2001, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5474),
                            EmployeeId = 30,
                            FirstName = "Madison",
                            LastName = "Powell",
                            Relationship = 2
                        },
                        new
                        {
                            Id = 104,
                            DateOfBirth = new DateTime(2003, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(5477),
                            EmployeeId = 30,
                            FirstName = "Mason",
                            LastName = "Long",
                            Relationship = 2
                        });
                });

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1960, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4639),
                            FirstName = "Charlotte",
                            LastName = "Johnson",
                            Salary = 103027m
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1999, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4709),
                            FirstName = "William",
                            LastName = "Williams",
                            Salary = 134500m
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1977, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4714),
                            FirstName = "Amelia",
                            LastName = "Brown",
                            Salary = 108453m
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1988, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4716),
                            FirstName = "James",
                            LastName = "Jones",
                            Salary = 75513m
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1960, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4720),
                            FirstName = "Harper",
                            LastName = "Garcia",
                            Salary = 78857m
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1988, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4725),
                            FirstName = "Benjamin",
                            LastName = "Miller",
                            Salary = 57522m
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1993, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4728),
                            FirstName = "Evelyn",
                            LastName = "Davis",
                            Salary = 51454m
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1993, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4731),
                            FirstName = "Lucas",
                            LastName = "Rodriguez",
                            Salary = 121082m
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1991, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4734),
                            FirstName = "Abigail",
                            LastName = "Martinez",
                            Salary = 71628m
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1992, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4737),
                            FirstName = "Henry",
                            LastName = "Hernandez",
                            Salary = 141530m
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1994, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4740),
                            FirstName = "Ella",
                            LastName = "Lopez",
                            Salary = 106734m
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1975, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4742),
                            FirstName = "Alexander",
                            LastName = "Gonzalez",
                            Salary = 133473m
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1992, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4745),
                            FirstName = "Mia",
                            LastName = "Wilson",
                            Salary = 149168m
                        },
                        new
                        {
                            Id = 14,
                            DateOfBirth = new DateTime(1968, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4748),
                            FirstName = "Michael",
                            LastName = "Anderson",
                            Salary = 120879m
                        },
                        new
                        {
                            Id = 15,
                            DateOfBirth = new DateTime(1989, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4751),
                            FirstName = "Scarlett",
                            LastName = "Thomas",
                            Salary = 78556m
                        },
                        new
                        {
                            Id = 16,
                            DateOfBirth = new DateTime(1965, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4754),
                            FirstName = "Elijah",
                            LastName = "Taylor",
                            Salary = 104481m
                        },
                        new
                        {
                            Id = 17,
                            DateOfBirth = new DateTime(1998, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4756),
                            FirstName = "Aria",
                            LastName = "Moore",
                            Salary = 97525m
                        },
                        new
                        {
                            Id = 18,
                            DateOfBirth = new DateTime(1971, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4760),
                            FirstName = "Jackson",
                            LastName = "Jackson",
                            Salary = 101094m
                        },
                        new
                        {
                            Id = 19,
                            DateOfBirth = new DateTime(1996, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4762),
                            FirstName = "Grace",
                            LastName = "Martin",
                            Salary = 61107m
                        },
                        new
                        {
                            Id = 20,
                            DateOfBirth = new DateTime(1968, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4765),
                            FirstName = "Sebastian",
                            LastName = "Lee",
                            Salary = 126266m
                        },
                        new
                        {
                            Id = 21,
                            DateOfBirth = new DateTime(1985, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4768),
                            FirstName = "Chloe",
                            LastName = "Perez",
                            Salary = 110980m
                        },
                        new
                        {
                            Id = 22,
                            DateOfBirth = new DateTime(1979, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4770),
                            FirstName = "Aiden",
                            LastName = "Thompson",
                            Salary = 63298m
                        },
                        new
                        {
                            Id = 23,
                            DateOfBirth = new DateTime(1966, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4773),
                            FirstName = "Sofia",
                            LastName = "White",
                            Salary = 101600m
                        },
                        new
                        {
                            Id = 24,
                            DateOfBirth = new DateTime(1978, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4814),
                            FirstName = "Matthew",
                            LastName = "Harris",
                            Salary = 145548m
                        },
                        new
                        {
                            Id = 25,
                            DateOfBirth = new DateTime(1994, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4817),
                            FirstName = "Riley",
                            LastName = "Sanchez",
                            Salary = 126631m
                        },
                        new
                        {
                            Id = 26,
                            DateOfBirth = new DateTime(1977, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4820),
                            FirstName = "Samuel",
                            LastName = "Clark",
                            Salary = 98823m
                        },
                        new
                        {
                            Id = 27,
                            DateOfBirth = new DateTime(1983, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4823),
                            FirstName = "Victoria",
                            LastName = "Ramirez",
                            Salary = 86465m
                        },
                        new
                        {
                            Id = 28,
                            DateOfBirth = new DateTime(1984, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4826),
                            FirstName = "David",
                            LastName = "Lewis",
                            Salary = 53455m
                        },
                        new
                        {
                            Id = 29,
                            DateOfBirth = new DateTime(1992, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4828),
                            FirstName = "Lily",
                            LastName = "Robinson",
                            Salary = 60374m
                        },
                        new
                        {
                            Id = 30,
                            DateOfBirth = new DateTime(1998, 5, 24, 21, 52, 27, 990, DateTimeKind.Local).AddTicks(4831),
                            FirstName = "Joseph",
                            LastName = "Walker",
                            Salary = 130833m
                        });
                });

            modelBuilder.Entity("Api.Models.Dependent", b =>
                {
                    b.HasOne("Api.Models.Employee", "Employee")
                        .WithMany("Dependents")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Api.Models.Employee", b =>
                {
                    b.Navigation("Dependents");
                });
#pragma warning restore 612, 618
        }
    }
}
